// genwallet creates fresh Solana and EVM wallets for the bot and appends the keys to .env.
// Private keys are written only to .env (gitignored) and never printed; existing keys are kept.
//
//	go run ./cmd/genwallet
package main

import (
	"crypto/ed25519"
	"crypto/rand"
	"fmt"
	"log"
	"os"
	"strings"

	gethcrypto "github.com/ethereum/go-ethereum/crypto"
	"github.com/joho/godotenv"
	"github.com/mr-tron/base58"
)

func main() {
	const path = ".env"
	env, err := godotenv.Read(path)
	if err != nil {
		log.Fatalf("read %s: %v", path, err)
	}

	var lines []string

	if env["SVM_WALLET_PRIVATE_KEY"] == "" {
		pub, priv, err := ed25519.GenerateKey(rand.Reader)
		if err != nil {
			log.Fatal(err)
		}
		addr := base58.Encode(pub)
		lines = append(lines, "SVM_WALLET_PUBLIC_KEY="+addr, "SVM_WALLET_PRIVATE_KEY="+base58.Encode(priv))
		fmt.Println("Solana address:", addr)
	} else {
		fmt.Println("Solana key already set, keeping it:", env["SVM_WALLET_PUBLIC_KEY"])
	}

	if env["EVM_WALLET_PRIVATE_KEY"] == "" {
		pk, err := gethcrypto.GenerateKey()
		if err != nil {
			log.Fatal(err)
		}
		addr := gethcrypto.PubkeyToAddress(pk.PublicKey).Hex()
		lines = append(lines, "EVM_WALLET_PUBLIC_KEY="+addr, "EVM_WALLET_PRIVATE_KEY="+fmt.Sprintf("%x", gethcrypto.FromECDSA(pk)))
		fmt.Println("EVM address:   ", addr, "(same address on Base, Ethereum, Arbitrum, BNB, Robinhood)")
	} else {
		fmt.Println("EVM key already set, keeping it:", env["EVM_WALLET_PUBLIC_KEY"])
	}

	if len(lines) == 0 {
		return
	}
	f, err := os.OpenFile(path, os.O_APPEND|os.O_WRONLY, 0o600)
	if err != nil {
		log.Fatalf("open %s: %v", path, err)
	}
	defer f.Close()
	if _, err := f.WriteString("\n# Jasmine wallets (generated by cmd/genwallet)\n" + strings.Join(lines, "\n") + "\n"); err != nil {
		log.Fatal(err)
	}
	fmt.Println("Private keys saved to .env only. Back them up somewhere safe; they are not printed.")
}
